backend:
  name: github
  branch: main
  repo: CnedTeamDev/site-secours
  base_url: "https://cnedteamdev.github.io/site-secours"
  auth_endpoint: "api/auth"
media_folder: "assets/uploads"
publish_mode: editorial_workflow
site_url: "https://cnedteamdev.github.io/site-secours"
logo_url: "https://cnedteamdev.github.io/site-secours/assets/img/logo-cned.png"
collections:
  - name: "alertes"
    label: "Alertes"
    folder: "content/alertes"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu de l’alerte", name: "body", widget: "markdown" }
